In [4]:
# Day 1 - 11, 15, 10, 6
# Day 2 - 10, 14, 11, 5
# Day 3 - 12, 17, 12, 8
# Day 4 - 15, 18, 14, 9

import numpy as np

In [14]:
twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])

twoDArray ## time complexity O(1), space complexity O(mn)

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

#### Insertion in 2D array

In [16]:
twoDArray

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

In [7]:
# First, state the index, e.g., 0
# axis = 1 for column insertion and axis = 0 for row insertion
newTwoDArray = np.insert(twoDArray, 0, [[1,2,3,4]], axis=1)

newTwoDArray

array([[ 1, 11, 15, 10,  6],
       [ 2, 10, 14, 11,  5],
       [ 3, 12, 17, 12,  8],
       [ 4, 15, 18, 14,  9]])

In [8]:
newTwoDArray = np.insert(twoDArray, 0, [[1,2,3,4]], axis=0)

newTwoDArray

array([[ 1,  2,  3,  4],
       [11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

In [17]:
# Add row at end of array
# Time complexity is O(1) in this case not O(mn)
newTwoDArray = np.append(twoDArray, [[1,2,3,4]], axis=0)

newTwoDArray

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9],
       [ 1,  2,  3,  4]])

#### Accessing an element in 2D Array

In [18]:
twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])

twoDArray

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

In [20]:
# len(array[0]) returns number of columns

def accessElements(array, rowIndex, colIndex):
    if rowIndex >= len(array) and colIndex >= len(array[0]):
        print("Incorrect index")
    else:
        print(array[rowIndex][colIndex])
        
accessElements(twoDArray, 1, 2)

11


In [21]:
accessElements(twoDArray, 2, 3)

8


#### Traversing through a 2D Array

In [22]:
twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])

twoDArray

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

In [23]:
def traverseTDArray(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])
            
traverseTDArray(twoDArray)

11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


#### Searching 2D Array

In [24]:
twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])

twoDArray

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

In [29]:
def searchTDArray(array, value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == value:
                return "The value is located at index " + str(i) + " " + str(j)
    return "The element is not found"

searchTDArray(twoDArray, 8)

'The value is located at index 2 3'

#### Deletion in 2D Array

In [30]:
twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])

twoDArray

array([[11, 15, 10,  6],
       [10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])

In [34]:
# Deleting first column
newTDArray = np.delete(twoDArray, 0, axis=1)
newTDArray

array([[15, 10,  6],
       [14, 11,  5],
       [17, 12,  8],
       [18, 14,  9]])

In [33]:
# Deleting first row
newTDArray = np.delete(twoDArray, 0, axis=0)
newTDArray

array([[10, 14, 11,  5],
       [12, 17, 12,  8],
       [15, 18, 14,  9]])