In [ ]:
# Question 1 uses arithmetic progression where Sn = n ( (a1 + an) / 2 ), n is the number of terms being added,
# a1 is the first term, an is the nth term (last term).
# Thus, n = 20, a1 = 1, an = 20 --> n(n+1)/2

In [8]:
# Question 1 - Missing Number
myList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20] # where 1+2+3+...+n = n(n+1)/2

def findMissingNumber(myList, n):
    arithmeticSum = n*(n+1)/2
    listSum = sum(myList)
    return arithmeticSum - listSum

findMissingNumber(myList, 20)

13.0

#### Question 2 - Two Sum
Write a program to find all pairs of integers whose sum is equal to a given number.
- Given an array of integers `num` and an integer `target`, return indices of the 2 numbers such that they add up to `target`.
- Assume that each input would have **exactly one solution**, and you may not use the same element twice.
- Can return the answer in any order.
###### Questions to ask:
- Does array contain only positive or negative numbers?
- What if the same pair repeats twice, should we print it every time?
- If the reverse of the pair is acceptable, e.g., can we print both (4, 1) and (1, 4) if the given sum is 5.
- Do we need to print only distinct pairs? Is (3, 3) a valid pair for given sum of 6?
- How big is the array?

In [3]:
# Question 2 - Two Sum (My Solution)
def twoSum(myList, target):
    resultList = []
    for i in range(len(myList)):
        for j in range(i+1, len(myList)):
            
            if myList[i] + myList[j] == target:
                resultList.append(i)
                resultList.append(j)
                return resultList
            
    return "No Result"

givenList = [3, 2, 3]
target = 6
twoSum(givenList, target)

[0, 2]

In [13]:
# Question 2 - Two Sum (Teacher's Solution - assume distinct pairs)
def findPairs(nums, target):
    for i in range(len(nums)):
        for j in range(i+1, len(nums)):
            # assume distict pairs (so disallow similar pairs)
            if nums[i] == nums[j]:
                continue
            elif nums[i] + nums[j] == target:
                print(i, j)
                
myList = [1,2,3,2,3,4,5,6]

findPairs(myList, 6)

0 6
1 5
3 5


In [24]:
# Question 3 - How to check if an array contains a number in Python?
import numpy as np
myArray = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

def findNumber(array, number):
    for i in range(len(array)):
        if array[i] == number:
            return "{} exists in the array".format(number)
    return "This number does not exist in the array."
            
findNumber(myArray, 13)

'13 exists in the array'

In [24]:
# Question 4 - How to find maximum product of 2 integers in the array where all elements are positive?
import numpy as np
myArray = np.array([1, 20, 30, 44, 5, 56, 57, 8, 9, 10, 31, 12, 13, 14, 35, 16, 27, 58, 19, 21])

def maximumProduct(array):
    highest = 0
    secondHighest = 0
    for i in range(len(array)):
        if array[i] > highest:
            highest = array[i]
            #array.remove(highest)
    
    for i in range(len(array)):
        if array[i] > secondHighest and array[i] != highest:
            secondHighest = array[i]
        
    return highest * secondHighest

maximumProduct(myArray)

3306

In [26]:
# Question 4 (Teacher's solution)
myArray = np.array([1, 20, 30, 44, 5, 56, 57, 8, 9, 10, 31, 12, 13, 14, 35, 16, 27, 58, 19, 21])

def findMaxProduct(array):
    maxProduct = 0
    for i in range(len(array)):
        for j in range(i+1, len(array)):
            if array[i] * array[j] > maxProduct:
                maxProduct = array[i] * array[j]
    return maxProduct

findMaxProduct(myArray)

3306

In [30]:
# Question 5 - Is Unique: Implement an algorithm to determine if a list has all unique charcaters, using Python list
myList = [1, 20, 30, 44, 5, 56, 57, 8, 19, 10, 31, 12, 13, 14, 35, 16, 27, 58, 19, 21]

def isUnique(ls):
    resultList = []
    for i in ls:
        if i not in resultList:
            resultList.append(i)
        else:
            print("{} is duplicated".format(i))
            return False
    return resultList

isUnique(myList)

19 is duplicated


False

In [34]:
# Question 6 - Permutation
def permutation(list1, list2):
    if len(list1) != len(list2):
        return False
    
    list1.sort()
    list2.sort()
    if list1 == list2:
        return True
    else:
        return False
    
list1 = [1,2,3]
list2 = [1,3,2]
permutation(list1, list2)

True

In [43]:
# Question7 - Rotate Matrix
import numpy as np
myArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

def rotateMatrix(matrix):
    # to find number of rows
    n = len(matrix)
    
    for layer in range(n // 2):
        first = layer
        last = n - layer - 1
        for i in range(first, last):
            # save top element
            top = matrix[layer][i]
            # move left element to top
            matrix[layer][i] = matrix[-i-1][layer]
            # move bottom element to left
            matrix[-i-1][layer] = matrix[-layer-1][-i-1]
            # move right element to bottom
            matrix[-layer-1][-i-1] = matrix[i][-layer-1]
            # move top to right
            matrix[i][-layer-1] = top
    return matrix

print(myArray, "\n")
rotateMatrix(myArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [2]:
value = 121

def isPalindrome(value):
    valueString = str(value)
    resultString = ""
    
    if len(valueString) == 0:
        return True
    
    if valueString[0] != valueString[len(valueString) - 1]:
        return False
    
    return isPalindrome(valueString[1:-1])

isPalindrome(90709)

True